version: '1.0'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes: 
    - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: